"""Add score column to task

Revision ID: 664efb246759
Revises: 2b517f3d32b8
Create Date: 2025-04-08 15:33:26.911255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '664efb246759'
down_revision: Union[str, None] = '2b517f3d32b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('score', sa.Integer(), nullable=False))
    op.alter_column('task', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'task', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='unique')
    op.alter_column('task', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('task', 'score')
    # ### end Alembic commands ###
